[package]
name = "faisanth"
version = "0.6.0"
edition = "2021"
description = "FAISANTH - Computational Routing Engine, Graph, Y-Bus, Optimizer (The Last Dance)"
license = "Unlicense"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
nalgebra = { workspace = true }
ndarray = { workspace = true }
uuid = { workspace = true }
